name: Exercice - Action Marketplace et Secret

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      # Utilisation d’un secret (sans l’afficher)
      - name: Utiliser un secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "Le secret n'est pas défini"
          else
            echo "Le secret API_KEY est bien chargé"
          fi
